### ISSUE TITLE
Typeahead component in s-forms demo causes whole form to fail

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#236]
To simulate the issue, do the following:
- go to [SForms storybook live](https://deploy-preview-232--s-forms-kbss.netlify.app/?path=/story/stories-forms--form-1)
- go to domain specific questions and play with questions for a while (e.g. going to calendar)
- following error will occur:
```
TypeError: options.sort is not a function
    at processTypeaheadOptions (https://deploy-preview-232--s-forms-kbss.netlify.app/284.7c4c3ec1.iframe.bundle.js:2:51129)
    at TypeaheadAnswer (https://deploy-preview-232--s-forms-kbss.netlify.app/284.7c4c3ec1.iframe.bundle.js:2:51784)
...
```

The screenshot:
![image](https://github.com/kbss-cvut/s-forms/assets/3962237/bb073e35-ede1-4010-ae3b-918c538a5dd4)

**Comment by blcham** [comment]
May be duplicate of https://github.com/kbss-cvut/s-forms/issues/219
